name: Test
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        container: node:14

        services:
            postgres:
                image: postgres:10.7
                env:
                    POSTGRES_PASSWORD: postgres
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - name: Checkout repository code
              uses: actions/checkout@v2
            
            - name: Install Dependencies
              run:  yarn install
            
            - name: Run Tests
              run:  yarn test
              env:
                DB_SCHEMA: postgres
                DB_HOST: postgres
                DB_PASSWORD: postgres